FUEL_DESIGNATORS = [
    'City',
    'Highway',
    'Combined',
    'CO2 Emissions',
    'CO2 Emissions (Combined)',
    'Low',
    'CO2 Emissions (Low)',
    'Medium',
    'CO2 Emissions (Medium)',
    'High',
    'CO2 Emissions (High)',
    'Extra high',
    'CO2 Emissions (Extra high)']

ALL_CAR_MAKES = ['Abarth', 'Acura', 'Alfa Romeo', 'Aston Martin', 'Audi', 'Bentley', 'BMW', 'Citroën', 'Dacia',
          'Dodge', 'DS Automobiles', 'Ferrari', 'Fiat', 'Ford', 'Honda', 'Hyundai', 'Infiniti', 'Jaguar', 'Jeep',
          'Kia', 'Lancia', 'Land Rover', 'Lexus', 'Maserati', 'Mazda', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
          'Opel', 'Peugeot', 'Porsche', 'Renault', 'Seat', 'Škoda', 'Smart', 'Subaru', 'Suzuki', 'Toyota',
          'Volkswagen', 'Volvo', 'Tesla']

WRITTEN_CSV_COLUMNS = [
    'Make',
    'Model',
    'Body',
    'Name',
    'Power',
    'Cylinders',
    'Electrical motor power',
    'Electrical motor torque',
    'Fuel',
    'Fuel capacity',
    'Top Speed',
    'Acceleration 0-62 Mph (0-100 kph)',
    'Drive Type',
    'Front',
    'Rear',
    'Tire Size',
    'Length',
    'Width',
    'Height',
    'Front/rear Track',
    'Wheelbase',
    'Ground Clearance',
    'Aerodynamics (Cd)',
    'Unladen Weight',
    'Gross Weight Limit',
    'Power pack',
    'Displacement',
    'Torque',
    'Fuel System',
    'Gearbox',
    'Total maximum power',
    'Cargo Volume',
    'Turning circle',
    'Turning circle (curb to curb)',
    'Turning circle (wall to wall)',
    'Total maximum torque',
    'Nominal Capacity',
    'Top speed (electrical)',
    'Maximum Capacity',
    'Fuel capacity (optional)',
    'Low (WLTP)',
    'Extra high (WLTP)',
    'Charger type',
    'Aerodynamics (frontal area)',
    'Combined (WLTP)',
    'CO2 Emissions (Low) (WLTP)',
    'High (WLTP)',
    'Medium (WLTP)',
    'CO2 Emissions (Medium) (WLTP)',
    'CO2 Emissions (Combined) (WLTP)',
    'CO2 Emissions (High) (WLTP)',
    'CO2 Emissions (Extra high) (WLTP)',
    'CO2 Emissions (NEDC)',
    'City (NEDC)',
    'Highway (NEDC)',
    'Combined (NEDC)',
    'Charging time (normal)',
    'Charging time (quick)',
    'Range',
    'Notice']
